import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language=ts sites/simji/app/utils/appwrite-types.ts`.

export enum Status {
    NEW = "new",
    PROCESSING = "processing",
    COMPLETE = "complete",
    ERROR = "error"
}

export type Presets = Models.Row & {
    name: string;
    description: string;
    prompt: string;
    category: string | null;
    tags: string[] | null;
    preview: string;
    previewUrl: string;
}

export type Purchases = Models.Row & {
    preset: Presets;
    status: Status;
    selfieId: string;
    owner: string;
    artifactId: string | null;
}
